/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.users;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author vanreach
 */
public class ContentForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContentForm
     */
    public ContentForm() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        setSize(1580, 1000);
        jPanel1.setSize(1024, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        UserCardItem = new views.users.CardItem();
        cardItem3 = new views.users.CardItem();
        cardItem2 = new views.users.CardItem();
        cardItem1 = new views.users.CardItem();
        jPanel3 = new javax.swing.JPanel();
        cardItem5 = new views.users.CardItem();
        cardItem6 = new views.users.CardItem();
        cardItem7 = new views.users.CardItem();
        cardItem8 = new views.users.CardItem();

        setPreferredSize(new java.awt.Dimension(1024, 483));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 381));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1024, 253));
        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 5, 0));

        UserCardItem.setBackground(new java.awt.Color(255, 255, 255));
        UserCardItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        UserCardItem.setPhoto(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        UserCardItem.setPreferredSize(new java.awt.Dimension(1024, 172));
        UserCardItem.setTitle("User");
        UserCardItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserCardItemMouseClicked(evt);
            }
        });
        jPanel2.add(UserCardItem);

        cardItem3.setBackground(new java.awt.Color(255, 255, 255));
        cardItem3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        cardItem3.setPhoto(new javax.swing.ImageIcon(getClass().getResource("/Image/Home-icon.png"))); // NOI18N
        cardItem3.setPreferredSize(new java.awt.Dimension(1024, 172));
        cardItem3.setTitle("Product");
        cardItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardItem3MouseClicked(evt);
            }
        });
        jPanel2.add(cardItem3);

        cardItem2.setBackground(new java.awt.Color(255, 255, 255));
        cardItem2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        cardItem2.setPhoto(new javax.swing.ImageIcon(getClass().getResource("/Image/category-8.png"))); // NOI18N
        cardItem2.setPreferredSize(new java.awt.Dimension(1024, 172));
        cardItem2.setTitle("Category");
        cardItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardItem2MouseClicked(evt);
            }
        });
        jPanel2.add(cardItem2);

        cardItem1.setBackground(new java.awt.Color(255, 255, 255));
        cardItem1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        cardItem1.setPhoto(new javax.swing.ImageIcon(getClass().getResource("/Image/4908317-200.png"))); // NOI18N
        cardItem1.setTitle("Supplier");
        cardItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardItem1MouseClicked(evt);
            }
        });
        jPanel2.add(cardItem1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1024, 253));
        jPanel3.setLayout(new java.awt.GridLayout(1, 4, 5, 0));

        cardItem5.setBackground(new java.awt.Color(255, 255, 255));
        cardItem5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        cardItem5.setPhoto(new javax.swing.ImageIcon(getClass().getResource("/Image/folder-users-icon.png"))); // NOI18N
        cardItem5.setPreferredSize(new java.awt.Dimension(1024, 172));
        cardItem5.setTitle("Account Type");
        cardItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardItem5MouseClicked(evt);
            }
        });
        jPanel3.add(cardItem5);

        cardItem6.setBackground(new java.awt.Color(255, 255, 255));
        cardItem6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        cardItem6.setPreferredSize(new java.awt.Dimension(1024, 172));
        cardItem6.setTitle("");
        jPanel3.add(cardItem6);

        cardItem7.setBackground(new java.awt.Color(255, 255, 255));
        cardItem7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        cardItem7.setPreferredSize(new java.awt.Dimension(1024, 172));
        cardItem7.setTitle("");
        jPanel3.add(cardItem7);

        cardItem8.setBackground(new java.awt.Color(255, 255, 255));
        cardItem8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        cardItem8.setTitle("");
        jPanel3.add(cardItem8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 2071, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(251, 251, 251)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(63, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserCardItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserCardItemMouseClicked
        MainForm.showForm(new UserForm());

    }//GEN-LAST:event_UserCardItemMouseClicked

    private void cardItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardItem3MouseClicked
        MainForm.showForm(new ProductForm());

    }//GEN-LAST:event_cardItem3MouseClicked

    private void cardItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardItem2MouseClicked
        MainForm.showForm(new CategoryForm());
    }//GEN-LAST:event_cardItem2MouseClicked

    private void cardItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardItem1MouseClicked
        MainForm.showForm(new SupplierForm());
    }//GEN-LAST:event_cardItem1MouseClicked

    private void cardItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardItem5MouseClicked
        MainForm.showForm(new accountForm());
    }//GEN-LAST:event_cardItem5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.users.CardItem UserCardItem;
    private views.users.CardItem cardItem1;
    private views.users.CardItem cardItem2;
    private views.users.CardItem cardItem3;
    private views.users.CardItem cardItem5;
    private views.users.CardItem cardItem6;
    private views.users.CardItem cardItem7;
    private views.users.CardItem cardItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
